
#ifndef __NET_ERRCODE_H__
#define __NET_ERRCODE_H__

#define BLE_ERROR_CODE_BASE (0x20000)
#define BLE_ERROR_CODE_HEAD_ERROR (BLE_ERROR_CODE_BASE + 1)
#define BLE_ERROR_CODE_PAYLOAD_LEN_ERROR (BLE_ERROR_CODE_BASE + 2)
#define BLE_ERROR_CODE_CHECKCODE_ERROR (BLE_ERROR_CODE_BASE + 3)
#define BLE_ERROR_CODE_CMD_ERROR (BLE_ERROR_CODE_BASE + 4)
#define BLE_ERROR_CODE_NETINFO_NOTCOMPLETE (BLE_ERROR_CODE_BASE + 5)

#endif